# This is a basic workflow to help you get started with Actions

name: basic workflow
on: workflow_dispatch
jobs:
  fisrt-job:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting
        run: echo "Hello World"
      - name : Good bye
        run : echo "done yet"
      
    
    


